package com.xiaoACE.ssm.entity.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.information
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    private String information;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.information
     *
     * @return the value of sys_role.information
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public String getinformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.information
     *
     * @param information the value for sys_role.information
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    public void setinformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    //用户
    private User user;
    //用户_角色
    private User_RoleKey user_roleKey;
}