package com.xiaoACE.ssm.entity.mapper;

import com.xiaoACE.ssm.entity.model.User_RoleKey;

public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    int deleteByPrimaryKey(User_RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    int insert(User_RoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Thu Jun 16 09:20:54 CST 2022
     */
    int insertSelective(User_RoleKey record);
}